//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Programlama_Dersi_Proje_Ödevi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Sepet = new HashSet<Sepet>();
        }
    
        public int AracId { get; set; }
        [DisplayName(" Araç Modeli ")]
        public string AracModel { get; set; }
        [DisplayName(" Araç Fiyatı")]
        public string AracFiyat { get; set; }
        [DisplayName(" Araç Türü ")]
        public string AracTuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet> Sepet { get; set; }
    }
}
