//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Programlama_Dersi_Proje_Ödevi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sepet
    {
        [DisplayName("Kiralayan Kişi")]
        public int SepetUserID { get; set; }
        [DisplayName("Kiralanan Araç")]
        public int SepetAracId { get; set; }

        [DisplayName(" Alım Tarihi")]

        public string SepetAlimTarihi { get; set; }
        [DisplayName("Teslim Tarihi")]
        public string SepetTeslimTarihi { get; set; }
        public int SepetID { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual User User { get; set; }
    }
}
