//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Programlama_Dersi_Proje_Ödevi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class hometext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hometext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Programlama_Dersi_Proje_Ödevi.Resources.hometext", typeof(hometext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Durumu.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemi İptal Et.
        /// </summary>
        public static string adminsepettencikar {
            get {
                return ResourceManager.GetString("adminsepettencikar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya Üniversitesi Teknokent A Blok No:24.
        /// </summary>
        public static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad - Soyad.
        /// </summary>
        public static string AdSoyad {
            get {
                return ResourceManager.GetString("AdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanında Uzman Teknisyenlerimiz İle 7/24 destek sağlıyoruz..
        /// </summary>
        public static string AlanındaUzman {
            get {
                return ResourceManager.GetString("AlanındaUzman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alım Tarihi.
        /// </summary>
        public static string AlimTarihi {
            get {
                return ResourceManager.GetString("AlimTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç Fiyatı.
        /// </summary>
        public static string AracFiyat {
            get {
                return ResourceManager.GetString("AracFiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aracı Sil.
        /// </summary>
        public static string aracisil {
            get {
                return ResourceManager.GetString("aracisil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçlar.
        /// </summary>
        public static string Araclar {
            get {
                return ResourceManager.GetString("Araclar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araçları Görüntüle.
        /// </summary>
        public static string AraclariGoruntule {
            get {
                return ResourceManager.GetString("AraclariGoruntule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç Modeli.
        /// </summary>
        public static string AracModel {
            get {
                return ResourceManager.GetString("AracModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Araç Türü.
        /// </summary>
        public static string AracTuru {
            get {
                return ResourceManager.GetString("AracTuru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAU-CAR AVRUPANIN HERYERİNDE......
        /// </summary>
        public static string baslik {
            get {
                return ResourceManager.GetString("baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizim İçin Para Her Zaman İkinci Planda... Öneml Olan Siz Değerli Müşterilerimiz....
        /// </summary>
        public static string BizimİçinPara {
            get {
                return ResourceManager.GetString("BizimİçinPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle İletişime Geçin.
        /// </summary>
        public static string BizimleİletişimeGeçin {
            get {
                return ResourceManager.GetString("BizimleİletişimeGeçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizim Müşterilerimiz Asla Yolda Kalmıyor....
        /// </summary>
        public static string BizimMüşterilerimizAslaYoldaKalmıyor {
            get {
                return ResourceManager.GetString("BizimMüşterilerimizAslaYoldaKalmıyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyük Destek.
        /// </summary>
        public static string BüyükDestek {
            get {
                return ResourceManager.GetString("BüyükDestek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pzt - Cum 09:00 - 18:00.
        /// </summary>
        public static string calisma {
            get {
                return ResourceManager.GetString("calisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cıkış Yap.
        /// </summary>
        public static string CikisYap {
            get {
                return ResourceManager.GetString("CikisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha yeni, daha güvenli filo.
        /// </summary>
        public static string Dahayeni {
            get {
                return ResourceManager.GetString("Dahayeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar...
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Düzenle {
            get {
                return ResourceManager.GetString("Düzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string GeriDön {
            get {
                return ResourceManager.GetString("GeriDön", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük, haftalık, aylık, kısa ve uzun süreli araç kiralama.
        /// </summary>
        public static string Günlükhaftalık {
            get {
                return ResourceManager.GetString("Günlükhaftalık", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi Bir Sıkıntı İle Karşılaştığınız Zaman Bir Telefon Kadar Yakınınızdayız...
        /// </summary>
        public static string HerhangiBirSıkıntıİle {
            get {
                return ResourceManager.GetString("HerhangiBirSıkıntıİle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string KayitOl {
            get {
                return ResourceManager.GetString("KayitOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolay online rezervasyon.
        /// </summary>
        public static string Kolayonlinerezervasyon {
            get {
                return ResourceManager.GetString("Kolayonlinerezervasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string KullanıcıAdı {
            get {
                return ResourceManager.GetString("KullanıcıAdı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar...
        /// </summary>
        public static string Kullanıcılar {
            get {
                return ResourceManager.GetString("Kullanıcılar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıları Görüntüle.
        /// </summary>
        public static string KullanicilariGörüntüle {
            get {
                return ResourceManager.GetString("KullanicilariGörüntüle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız....
        /// </summary>
        public static string mesaj {
            get {
                return ResourceManager.GetString("mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajı Gönder ...
        /// </summary>
        public static string mesajıgönder {
            get {
                return ResourceManager.GetString("mesajıgönder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşterilerimize Sunduğumuz Hizmetler.
        /// </summary>
        public static string MüşterilerimizeSunduğumuzHizmetler {
            get {
                return ResourceManager.GetString("MüşterilerimizeSunduğumuzHizmetler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEDEN SAU-CAR ??.
        /// </summary>
        public static string nedensau {
            get {
                return ResourceManager.GetString("nedensau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Kolaylığı.
        /// </summary>
        public static string ÖdemeKolaylığı {
            get {
                return ResourceManager.GetString("ÖdemeKolaylığı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olumlu Yorumlar.
        /// </summary>
        public static string OlumluYorumlar {
            get {
                return ResourceManager.GetString("OlumluYorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesyonel Servis.
        /// </summary>
        public static string ProfesyonelServis {
            get {
                return ResourceManager.GetString("ProfesyonelServis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepet...
        /// </summary>
        public static string Sepet {
            get {
                return ResourceManager.GetString("Sepet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle...
        /// </summary>
        public static string sepeteekle {
            get {
                return ResourceManager.GetString("sepeteekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepeti Listele.
        /// </summary>
        public static string SepetiListele {
            get {
                return ResourceManager.GetString("SepetiListele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aracı Secin.
        /// </summary>
        public static string sepettekiaracisec {
            get {
                return ResourceManager.GetString("sepettekiaracisec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepetten Çıkar....
        /// </summary>
        public static string SepettenCıkar {
            get {
                return ResourceManager.GetString("SepettenCıkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞİFRE TEKRARI.
        /// </summary>
        public static string sifretekrarı {
            get {
                return ResourceManager.GetString("sifretekrarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ideas are important to us!.
        /// </summary>
        public static string Sizinfikirleriniz {
            get {
                return ResourceManager.GetString("Sizinfikirleriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizlerden Aldığımız Olumlu Yorumlar Sayesinde İşimizi Daha Severek Yapıyoruz...
        /// </summary>
        public static string SizlerdenAldığımızOlumluYorumlar {
            get {
                return ResourceManager.GetString("SizlerdenAldığımızOlumluYorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Beceriler.
        /// </summary>
        public static string TeknikBeceriler {
            get {
                return ResourceManager.GetString("TeknikBeceriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknisyenlerimiz İşlerini Büyük Bir Özveri İle Gerçekleştiriyor...
        /// </summary>
        public static string TeknisyenlerimizİşleriniBüyük {
            get {
                return ResourceManager.GetString("TeknisyenlerimizİşleriniBüyük", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Tarihi.
        /// </summary>
        public static string TeslimTarihi {
            get {
                return ResourceManager.GetString("TeslimTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygun fiyatlı kiralama seçenekleri.
        /// </summary>
        public static string Uygunfiyatlıkiralamaseçenekleri {
            get {
                return ResourceManager.GetString("Uygunfiyatlıkiralamaseçenekleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzman Teknisyenler.
        /// </summary>
        public static string UzmanTeknisyenler {
            get {
                return ResourceManager.GetString("UzmanTeknisyenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkiye’de araba kiralamak, ülkenin sunduğu vahşi ve çeşitli manzaraları keşfetmek için uygun maliyetli bir yoldur. Şehir arabalarından ve minibüslerden lüks kiralık araçlara kadar, SAUCAR , eğlencenizi en üst düzeye çıkarmanıza yardımcı olacak çok çeşitli modellere sahiptir. SAUCAR ’nın ülke geneline yayılmış 116 istasyonu vardır. En popüler toplama noktaları, Brisbane gibi şehirlerin yanı sıra sörfçü cenneti - Gold Coast boyunca bulunan istasyonları da içermektedir. Sydney Havaalanı ve Melbourne Havaalanı [rest of string was truncated]&quot;;.
        /// </summary>
        public static string yazi {
            get {
                return ResourceManager.GetString("yazi", resourceCulture);
            }
        }
    }
}
